# Generated by Django 5.2 on 2025-04-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_asset_portfolio_assetprice_portfolioassetweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='assetprice',
            unique_together={('asset', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='portfolioassetweight',
            unique_together={('asset', 'portfolio', 'date')},
        ),
    ]
