# Generated by Django 5.2 on 2025-04-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_assetprice_price_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assetprice',
            index=models.Index(fields=['date', 'asset'], name='api_assetpr_date_6ecd0f_idx'),
        ),
    ]
